.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.macro  EXPORT  name
  .globl \name
\name:
.endm

.rdata

.set REDISPATCH, 0x00
.set SW1, 0x04
.set SW2, 0x08
.set RCP, 0x0c
.set CART, 0x10
.set PRENMI, 0x14
.set IP6_HDLR, 0x18
.set IP7_HDLR, 0x1c
.set COUNTER, 0x20

__osIntOffTable:
    .byte REDISPATCH
    .byte PRENMI
    .byte IP6_HDLR
    .byte IP6_HDLR
    .byte IP7_HDLR
    .byte IP7_HDLR
    .byte IP7_HDLR
    .byte IP7_HDLR
    .byte COUNTER
    .byte COUNTER
    .byte COUNTER
    .byte COUNTER
    .byte COUNTER
    .byte COUNTER
    .byte COUNTER
    .byte COUNTER
    .byte REDISPATCH
    .byte SW1
    .byte SW2
    .byte SW2
    .byte RCP
    .byte RCP
    .byte RCP
    .byte RCP
    .byte CART
    .byte CART
    .byte CART
    .byte CART
    .byte CART
    .byte CART
    .byte CART
    .byte CART
    
__osIntTable:
    .word redispatch, sw1, sw2, rcp, cart, prenmi, IP6_Hdlr, IP7_Hdlr, counter

EXPORT __osCauseTable_pt
    .byte 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0
    .byte 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0

.data

EXPORT __osHwIntTable
    .word 0
    .word 0
    .word 0
    .word 0
    .word 0

__osRdb_DbgRead_Ct:
  .word 0

__osRdb_Mesg:
  .word 0

__os_Kdebug_Pkt:
  .word 0

.section .text, "ax"

/* Generated by spimdisasm 1.40.1 */

/* Handwritten function */

glabel __osExceptionPreamble
    /* 5DB10 8005CF10 3C1A8006 */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* 5DB14 8005CF14 275ACFE4 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* 5DB18 8005CF18 03400008 */  jr         $k0
    /* 5DB1C 8005CF1C 00000000 */   nop
endlabel __osExceptionPreamble

/* Handwritten function */

glabel __ptExceptionPreamble
    /* 5DB20 8005CF20 AFBAFFF0 */  sw         $k0, -0x10($sp) /* handwritten instruction */
    /* 5DB24 8005CF24 10000003 */  b          .L8005CF34
    /* 5DB28 8005CF28 3C1A8006 */   lui       $k0, %hi(__ptException) /* handwritten instruction */
    /* 5DB2C 8005CF2C 00000000 */  nop
    /* 5DB30 8005CF30 00000000 */  nop
  .L8005CF34:
    /* 5DB34 8005CF34 275ACF40 */  addiu      $k0, $k0, %lo(__ptException) /* handwritten instruction */
    /* 5DB38 8005CF38 03400008 */  jr         $k0
    /* 5DB3C 8005CF3C 00000000 */   nop
endlabel __ptExceptionPreamble

/* Handwritten function */

glabel __ptException
    /* 5DB40 8005CF40 401A6800 */  mfc0       $k0, $13 /* handwritten instruction */
    /* 5DB44 8005CF44 335A007C */  andi       $k0, $k0, 0x7C /* handwritten instruction */
    /* 5DB48 8005CF48 17400008 */  bnez       $k0, .L8005CF6C /* handwritten instruction */
    /* 5DB4C 8005CF4C 001AD082 */   srl       $k0, $k0, 2
    /* 5DB50 8005CF50 401A6800 */  mfc0       $k0, $13 /* handwritten instruction */
    /* 5DB54 8005CF54 00000000 */  nop
    /* 5DB58 8005CF58 335A4000 */  andi       $k0, $k0, 0x4000 /* handwritten instruction */
    /* 5DB5C 8005CF5C 13400021 */  beqz       $k0, __osException /* handwritten instruction */
    /* 5DB60 8005CF60 00000000 */   nop
    /* 5DB64 8005CF64 080173E2 */  j          .L8005CF88
    /* 5DB68 8005CF68 00000000 */   nop
  .L8005CF6C:
    /* 5DB6C 8005CF6C AFBBFFF8 */  sw         $k1, -0x8($sp) /* handwritten instruction */
    /* 5DB70 8005CF70 3C1B8008 */  lui        $k1, %hi(__osCauseTable_pt) /* handwritten instruction */
    /* 5DB74 8005CF74 277BEDE4 */  addiu      $k1, $k1, %lo(__osCauseTable_pt) /* handwritten instruction */
    /* 5DB78 8005CF78 037AD820 */  add        $k1, $k1, $k0 /* handwritten instruction */
    /* 5DB7C 8005CF7C 937A0000 */  lbu        $k0, 0x0($k1) /* handwritten instruction */
    /* 5DB80 8005CF80 13400018 */  beqz       $k0, __osException /* handwritten instruction */
    /* 5DB84 8005CF84 00000000 */   nop
  .L8005CF88:
    /* 5DB88 8005CF88 3C1AA460 */  lui        $k0, %hi(D_A4600010) /* handwritten instruction */
    /* 5DB8C 8005CF8C 8F5A0010 */  lw         $k0, %lo(D_A4600010)($k0) /* handwritten instruction */
    /* 5DB90 8005CF90 00000000 */  nop
    /* 5DB94 8005CF94 335A0003 */  andi       $k0, $k0, 0x3 /* handwritten instruction */
    /* 5DB98 8005CF98 1740FFFB */  bnez       $k0, .L8005CF88 /* handwritten instruction */
    /* 5DB9C 8005CF9C 00000000 */   nop
    /* 5DBA0 8005CFA0 3C1ABFF1 */  lui        $k0, %hi(D_BFF08004) /* handwritten instruction */
    /* 5DBA4 8005CFA4 8F5A8004 */  lw         $k0, %lo(D_BFF08004)($k0) /* handwritten instruction */
    /* 5DBA8 8005CFA8 00000000 */  nop
    /* 5DBAC 8005CFAC 335A0008 */  andi       $k0, $k0, 0x8 /* handwritten instruction */
    /* 5DBB0 8005CFB0 17400005 */  bnez       $k0, .L8005CFC8 /* handwritten instruction */
    /* 5DBB4 8005CFB4 3C1ABFF0 */   lui       $k0, (0xBFF00014 >> 16) /* handwritten instruction */
    /* 5DBB8 8005CFB8 375A0014 */  ori        $k0, $k0, (0xBFF00014 & 0xFFFF) /* handwritten instruction */
    /* 5DBBC 8005CFBC 8FBBFFF8 */  lw         $k1, -0x8($sp) /* handwritten instruction */
    /* 5DBC0 8005CFC0 03400008 */  jr         $k0
    /* 5DBC4 8005CFC4 27BDFFA0 */   addiu     $sp, $sp, -0x60
  .L8005CFC8:
    /* 5DBC8 8005CFC8 401A7000 */  mfc0       $k0, $14 /* handwritten instruction */
    /* 5DBCC 8005CFCC 3C1BBFF1 */  lui        $k1, %hi(D_BFF08000) /* handwritten instruction */
    /* 5DBD0 8005CFD0 AF7A8000 */  sw         $k0, %lo(D_BFF08000)($k1) /* handwritten instruction */
    /* 5DBD4 8005CFD4 8FBBFFF8 */  lw         $k1, -0x8($sp) /* handwritten instruction */
    /* 5DBD8 8005CFD8 8FBAFFF0 */  lw         $k0, -0x10($sp) /* handwritten instruction */
    /* 5DBDC 8005CFDC 42000018 */  eret /* handwritten instruction */
endlabel __ptException
    /* 5DBE0 8005CFE0 00000000 */  nop

/* Handwritten function */

glabel __osException
    /* 5DBE4 8005CFE4 3C1A800C */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
    /* 5DBE8 8005CFE8 275AEFB8 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
    /* 5DBEC 8005CFEC FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* 5DBF0 8005CFF0 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* 5DBF4 8005CFF4 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 5DBF8 8005CFF8 2401FFFC */  addiu      $at, $zero, -0x4
    /* 5DBFC 8005CFFC 0361D824 */  and        $k1, $k1, $at
    /* 5DC00 8005D000 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 5DC04 8005D004 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* 5DC08 8005D008 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 5DC0C 8005D00C FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* 5DC10 8005D010 AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* 5DC14 8005D014 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 5DC18 8005D018 3C0A800C */  lui        $t2, %hi(__kmc_pt_mode)
    /* 5DC1C 8005D01C 8D4AEFB0 */  lw         $t2, %lo(__kmc_pt_mode)($t2)
    /* 5DC20 8005D020 154000DD */  bnez       $t2, .L8005D398
    /* 5DC24 8005D024 00000000 */   nop
    /* 5DC28 8005D028 3109007C */  andi       $t1, $t0, 0x7C
    /* 5DC2C 8005D02C 240A0000 */  addiu      $t2, $zero, 0x0
    /* 5DC30 8005D030 152A00D9 */  bne        $t1, $t2, .L8005D398
    /* 5DC34 8005D034 00000000 */   nop
    /* 5DC38 8005D038 03684824 */  and        $t1, $k1, $t0
    /* 5DC3C 8005D03C 312A4000 */  andi       $t2, $t1, 0x4000
    /* 5DC40 8005D040 114000A3 */  beqz       $t2, .L8005D2D0
    /* 5DC44 8005D044 00000000 */   nop
    /* 5DC48 8005D048 3C09C000 */  lui        $t1, (0xC0000008 >> 16)
    /* 5DC4C 8005D04C 35290008 */  ori        $t1, $t1, (0xC0000008 & 0xFFFF)
    /* 5DC50 8005D050 AD200000 */  sw         $zero, 0x0($t1)
  .L8005D054:
    /* 5DC54 8005D054 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 5DC58 8005D058 31084000 */  andi       $t0, $t0, 0x4000
    /* 5DC5C 8005D05C 1408FFFD */  bne        $zero, $t0, .L8005D054
    /* 5DC60 8005D060 00000000 */   nop
    /* 5DC64 8005D064 3C0AC000 */  lui        $t2, (0xC0000000 >> 16)
    /* 5DC68 8005D068 8D480000 */  lw         $t0, (0xC0000000 & 0xFFFF)($t2)
    /* 5DC6C 8005D06C 00084E82 */  srl        $t1, $t0, 26
    /* 5DC70 8005D070 3129003F */  andi       $t1, $t1, 0x3F
    /* 5DC74 8005D074 240A0010 */  addiu      $t2, $zero, 0x10
    /* 5DC78 8005D078 112A0041 */  beq        $t1, $t2, .L8005D180
    /* 5DC7C 8005D07C 00000000 */   nop
    /* 5DC80 8005D080 240A000E */  addiu      $t2, $zero, 0xE
    /* 5DC84 8005D084 112A0066 */  beq        $t1, $t2, .L8005D220
    /* 5DC88 8005D088 00000000 */   nop
    /* 5DC8C 8005D08C 240A0014 */  addiu      $t2, $zero, 0x14
    /* 5DC90 8005D090 112A0022 */  beq        $t1, $t2, .L8005D11C
    /* 5DC94 8005D094 00000000 */   nop
    /* 5DC98 8005D098 240A000F */  addiu      $t2, $zero, 0xF
    /* 5DC9C 8005D09C 112A0022 */  beq        $t1, $t2, .L8005D128
    /* 5DCA0 8005D0A0 00000000 */   nop
    /* 5DCA4 8005D0A4 240A0011 */  addiu      $t2, $zero, 0x11
    /* 5DCA8 8005D0A8 112A0025 */  beq        $t1, $t2, .L8005D140
    /* 5DCAC 8005D0AC 00000000 */   nop
    /* 5DCB0 8005D0B0 240A000D */  addiu      $t2, $zero, 0xD
    /* 5DCB4 8005D0B4 112A0026 */  beq        $t1, $t2, .L8005D150
    /* 5DCB8 8005D0B8 00000000 */   nop
    /* 5DCBC 8005D0BC 240A0012 */  addiu      $t2, $zero, 0x12
    /* 5DCC0 8005D0C0 112A0027 */  beq        $t1, $t2, .L8005D160
    /* 5DCC4 8005D0C4 00000000 */   nop
    /* 5DCC8 8005D0C8 240A0013 */  addiu      $t2, $zero, 0x13
    /* 5DCCC 8005D0CC 112A0028 */  beq        $t1, $t2, .L8005D170
    /* 5DCD0 8005D0D0 00000000 */   nop
    /* 5DCD4 8005D0D4 240A0015 */  addiu      $t2, $zero, 0x15
    /* 5DCD8 8005D0D8 112A0003 */  beq        $t1, $t2, .L8005D0E8
    /* 5DCDC 8005D0DC 00000000 */   nop
    /* 5DCE0 8005D0E0 100000A2 */  b          .L8005D36C
    /* 5DCE4 8005D0E4 00000000 */   nop
  .L8005D0E8:
    /* 5DCE8 8005D0E8 240A0001 */  addiu      $t2, $zero, 0x1
    /* 5DCEC 8005D0EC 00084C02 */  srl        $t1, $t0, 16
    /* 5DCF0 8005D0F0 312900FF */  andi       $t1, $t1, 0xFF
    /* 5DCF4 8005D0F4 112A0005 */  beq        $t1, $t2, .L8005D10C
    /* 5DCF8 8005D0F8 00000000 */   nop
    /* 5DCFC 8005D0FC 240A00A8 */  addiu      $t2, $zero, 0xA8
    /* 5DD00 8005D100 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5DD04 8005D104 100000A4 */  b          .L8005D398
    /* 5DD08 8005D108 AC2A9628 */   sw        $t2, %lo(__osRdb_Mesg)($at)
  .L8005D10C:
    /* 5DD0C 8005D10C 240A00B0 */  addiu      $t2, $zero, 0xB0
    /* 5DD10 8005D110 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5DD14 8005D114 100000A0 */  b          .L8005D398
    /* 5DD18 8005D118 AC2A9628 */   sw        $t2, %lo(__osRdb_Mesg)($at)
  .L8005D11C:
    /* 5DD1C 8005D11C 3C018008 */  lui        $at, %hi(__os_Kdebug_Pkt)
    /* 5DD20 8005D120 1000009D */  b          .L8005D398
    /* 5DD24 8005D124 AC28962C */   sw        $t0, %lo(__os_Kdebug_Pkt)($at)
  .L8005D128:
    /* 5DD28 8005D128 3C0A00FF */  lui        $t2, (0xFFFFFF >> 16)
    /* 5DD2C 8005D12C 354AFFFF */  ori        $t2, $t2, (0xFFFFFF & 0xFFFF)
    /* 5DD30 8005D130 010A4824 */  and        $t1, $t0, $t2
    /* 5DD34 8005D134 3C018008 */  lui        $at, %hi(__osRdb_DbgRead_Ct)
    /* 5DD38 8005D138 1000008C */  b          .L8005D36C
    /* 5DD3C 8005D13C AC299624 */   sw        $t1, %lo(__osRdb_DbgRead_Ct)($at)
  .L8005D140:
    /* 5DD40 8005D140 240A0088 */  addiu      $t2, $zero, 0x88
    /* 5DD44 8005D144 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5DD48 8005D148 10000093 */  b          .L8005D398
    /* 5DD4C 8005D14C AC2A9628 */   sw        $t2, %lo(__osRdb_Mesg)($at)
  .L8005D150:
    /* 5DD50 8005D150 240A0080 */  addiu      $t2, $zero, 0x80
    /* 5DD54 8005D154 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5DD58 8005D158 1000008F */  b          .L8005D398
    /* 5DD5C 8005D15C AC2A9628 */   sw        $t2, %lo(__osRdb_Mesg)($at)
  .L8005D160:
    /* 5DD60 8005D160 240A0090 */  addiu      $t2, $zero, 0x90
    /* 5DD64 8005D164 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5DD68 8005D168 1000008B */  b          .L8005D398
    /* 5DD6C 8005D16C AC2A9628 */   sw        $t2, %lo(__osRdb_Mesg)($at)
  .L8005D170:
    /* 5DD70 8005D170 240A0098 */  addiu      $t2, $zero, 0x98
    /* 5DD74 8005D174 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5DD78 8005D178 10000087 */  b          .L8005D398
    /* 5DD7C 8005D17C AC2A9628 */   sw        $t2, %lo(__osRdb_Mesg)($at)
  .L8005D180:
    /* 5DD80 8005D180 00084E02 */  srl        $t1, $t0, 24
    /* 5DD84 8005D184 31290003 */  andi       $t1, $t1, 0x3
    /* 5DD88 8005D188 10090078 */  beq        $zero, $t1, .L8005D36C
    /* 5DD8C 8005D18C 00000000 */   nop
    /* 5DD90 8005D190 3C0A800E */  lui        $t2, %hi(__osRdb_Read_Data_Ct)
    /* 5DD94 8005D194 8D4A5CF8 */  lw         $t2, %lo(__osRdb_Read_Data_Ct)($t2)
    /* 5DD98 8005D198 01495023 */  subu       $t2, $t2, $t1
    /* 5DD9C 8005D19C 3C01800E */  lui        $at, %hi(__osRdb_Read_Data_Ct)
    /* 5DDA0 8005D1A0 AC2A5CF8 */  sw         $t2, %lo(__osRdb_Read_Data_Ct)($at)
    /* 5DDA4 8005D1A4 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 5DDA8 8005D1A8 3C0B8015 */  lui        $t3, %hi(__osRdb_Read_Data_Buf)
    /* 5DDAC 8005D1AC 8D6B4820 */  lw         $t3, %lo(__osRdb_Read_Data_Buf)($t3)
    /* 5DDB0 8005D1B0 00085402 */  srl        $t2, $t0, 16
    /* 5DDB4 8005D1B4 314A00FF */  andi       $t2, $t2, 0xFF
    /* 5DDB8 8005D1B8 A16A0000 */  sb         $t2, 0x0($t3)
    /* 5DDBC 8005D1BC 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
    /* 5DDC0 8005D1C0 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 5DDC4 8005D1C4 1009000B */  beq        $zero, $t1, .L8005D1F4
    /* 5DDC8 8005D1C8 00000000 */   nop
    /* 5DDCC 8005D1CC 00085202 */  srl        $t2, $t0, 8
    /* 5DDD0 8005D1D0 314A00FF */  andi       $t2, $t2, 0xFF
    /* 5DDD4 8005D1D4 A16A0000 */  sb         $t2, 0x0($t3)
    /* 5DDD8 8005D1D8 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
    /* 5DDDC 8005D1DC 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 5DDE0 8005D1E0 10090004 */  beq        $zero, $t1, .L8005D1F4
    /* 5DDE4 8005D1E4 00000000 */   nop
    /* 5DDE8 8005D1E8 310800FF */  andi       $t0, $t0, 0xFF
    /* 5DDEC 8005D1EC A1680000 */  sb         $t0, 0x0($t3)
    /* 5DDF0 8005D1F0 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
  .L8005D1F4:
    /* 5DDF4 8005D1F4 3C018015 */  lui        $at, %hi(__osRdb_Read_Data_Buf)
    /* 5DDF8 8005D1F8 AC2B4820 */  sw         $t3, %lo(__osRdb_Read_Data_Buf)($at)
    /* 5DDFC 8005D1FC DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* 5DE00 8005D200 3C0A800E */  lui        $t2, %hi(__osRdb_Read_Data_Ct)
    /* 5DE04 8005D204 8D4A5CF8 */  lw         $t2, %lo(__osRdb_Read_Data_Ct)($t2)
    /* 5DE08 8005D208 140A0058 */  bne        $zero, $t2, .L8005D36C
    /* 5DE0C 8005D20C 00000000 */   nop
    /* 5DE10 8005D210 240A0078 */  addiu      $t2, $zero, 0x78
    /* 5DE14 8005D214 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5DE18 8005D218 1000005F */  b          .L8005D398
    /* 5DE1C 8005D21C AC2A9628 */   sw        $t2, %lo(__osRdb_Mesg)($at)
  .L8005D220:
    /* 5DE20 8005D220 00084E02 */  srl        $t1, $t0, 24
    /* 5DE24 8005D224 31290003 */  andi       $t1, $t1, 0x3
    /* 5DE28 8005D228 10090050 */  beq        $zero, $t1, .L8005D36C
    /* 5DE2C 8005D22C 00000000 */   nop
    /* 5DE30 8005D230 3C0A8008 */  lui        $t2, %hi(__osRdb_DbgRead_Ct)
    /* 5DE34 8005D234 8D4A9624 */  lw         $t2, %lo(__osRdb_DbgRead_Ct)($t2)
    /* 5DE38 8005D238 01495023 */  subu       $t2, $t2, $t1
    /* 5DE3C 8005D23C 3C018008 */  lui        $at, %hi(__osRdb_DbgRead_Ct)
    /* 5DE40 8005D240 AC2A9624 */  sw         $t2, %lo(__osRdb_DbgRead_Ct)($at)
    /* 5DE44 8005D244 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 5DE48 8005D248 3C0B800C */  lui        $t3, %hi(__osRdb_DbgRead_Buf)
    /* 5DE4C 8005D24C 8D6B83CC */  lw         $t3, %lo(__osRdb_DbgRead_Buf)($t3)
    /* 5DE50 8005D250 140B0003 */  bne        $zero, $t3, .L8005D260
    /* 5DE54 8005D254 00000000 */   nop
    /* 5DE58 8005D258 10000044 */  b          .L8005D36C
    /* 5DE5C 8005D25C DF4B0070 */   ld        $t3, 0x70($k0) /* handwritten instruction */
  .L8005D260:
    /* 5DE60 8005D260 00085402 */  srl        $t2, $t0, 16
    /* 5DE64 8005D264 314A00FF */  andi       $t2, $t2, 0xFF
    /* 5DE68 8005D268 A16A0000 */  sb         $t2, 0x0($t3)
    /* 5DE6C 8005D26C 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
    /* 5DE70 8005D270 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 5DE74 8005D274 1009000B */  beq        $zero, $t1, .L8005D2A4
    /* 5DE78 8005D278 00000000 */   nop
    /* 5DE7C 8005D27C 00085202 */  srl        $t2, $t0, 8
    /* 5DE80 8005D280 314A00FF */  andi       $t2, $t2, 0xFF
    /* 5DE84 8005D284 A16A0000 */  sb         $t2, 0x0($t3)
    /* 5DE88 8005D288 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
    /* 5DE8C 8005D28C 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 5DE90 8005D290 10090004 */  beq        $zero, $t1, .L8005D2A4
    /* 5DE94 8005D294 00000000 */   nop
    /* 5DE98 8005D298 310800FF */  andi       $t0, $t0, 0xFF
    /* 5DE9C 8005D29C A1680000 */  sb         $t0, 0x0($t3)
    /* 5DEA0 8005D2A0 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
  .L8005D2A4:
    /* 5DEA4 8005D2A4 3C01800C */  lui        $at, %hi(__osRdb_DbgRead_Buf)
    /* 5DEA8 8005D2A8 AC2B83CC */  sw         $t3, %lo(__osRdb_DbgRead_Buf)($at)
    /* 5DEAC 8005D2AC DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* 5DEB0 8005D2B0 3C0A8008 */  lui        $t2, %hi(__osRdb_DbgRead_Ct)
    /* 5DEB4 8005D2B4 8D4A9624 */  lw         $t2, %lo(__osRdb_DbgRead_Ct)($t2)
    /* 5DEB8 8005D2B8 140A002C */  bne        $zero, $t2, .L8005D36C
    /* 5DEBC 8005D2BC 00000000 */   nop
    /* 5DEC0 8005D2C0 240A00A0 */  addiu      $t2, $zero, 0xA0
    /* 5DEC4 8005D2C4 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5DEC8 8005D2C8 10000033 */  b          .L8005D398
    /* 5DECC 8005D2CC AC2A9628 */   sw        $t2, %lo(__osRdb_Mesg)($at)
  .L8005D2D0:
    /* 5DED0 8005D2D0 312A2000 */  andi       $t2, $t1, 0x2000
    /* 5DED4 8005D2D4 11400030 */  beqz       $t2, .L8005D398
    /* 5DED8 8005D2D8 00000000 */   nop
    /* 5DEDC 8005D2DC 3C09C000 */  lui        $t1, (0xC000000C >> 16)
    /* 5DEE0 8005D2E0 3529000C */  ori        $t1, $t1, (0xC000000C & 0xFFFF)
    /* 5DEE4 8005D2E4 AD200000 */  sw         $zero, 0x0($t1)
    /* 5DEE8 8005D2E8 3C0A8015 */  lui        $t2, %hi(__osRdb_IP6_Ct)
    /* 5DEEC 8005D2EC 8D4A7500 */  lw         $t2, %lo(__osRdb_IP6_Ct)($t2)
    /* 5DEF0 8005D2F0 15400005 */  bnez       $t2, .L8005D308
    /* 5DEF4 8005D2F4 00000000 */   nop
    /* 5DEF8 8005D2F8 240A0001 */  addiu      $t2, $zero, 0x1
    /* 5DEFC 8005D2FC 3C018008 */  lui        $at, %hi(__osRdb_IP6_Empty)
    /* 5DF00 8005D300 1000001A */  b          .L8005D36C
    /* 5DF04 8005D304 AC2A9650 */   sw        $t2, %lo(__osRdb_IP6_Empty)($at)
  .L8005D308:
    /* 5DF08 8005D308 214AFFFF */  addi       $t2, $t2, -0x1 /* handwritten instruction */
    /* 5DF0C 8005D30C 3C018015 */  lui        $at, %hi(__osRdb_IP6_Ct)
    /* 5DF10 8005D310 AC2A7500 */  sw         $t2, %lo(__osRdb_IP6_Ct)($at)
    /* 5DF14 8005D314 3C088015 */  lui        $t0, %hi(__osRdb_IP6_Data)
    /* 5DF18 8005D318 8D086BD8 */  lw         $t0, %lo(__osRdb_IP6_Data)($t0)
    /* 5DF1C 8005D31C 3C098015 */  lui        $t1, %hi(__osRdb_IP6_CurSend)
    /* 5DF20 8005D320 8D29F348 */  lw         $t1, %lo(__osRdb_IP6_CurSend)($t1)
    /* 5DF24 8005D324 00095080 */  sll        $t2, $t1, 2
    /* 5DF28 8005D328 01484020 */  add        $t0, $t2, $t0 /* handwritten instruction */
    /* 5DF2C 8005D32C 8D0A0000 */  lw         $t2, 0x0($t0)
    /* 5DF30 8005D330 21290001 */  addi       $t1, $t1, 0x1 /* handwritten instruction */
    /* 5DF34 8005D334 3C08800E */  lui        $t0, %hi(__osRdb_IP6_Size)
    /* 5DF38 8005D338 8D086000 */  lw         $t0, %lo(__osRdb_IP6_Size)($t0)
    /* 5DF3C 8005D33C 01094022 */  sub        $t0, $t0, $t1 /* handwritten instruction */
    /* 5DF40 8005D340 1D000002 */  bgtz       $t0, .L8005D34C
    /* 5DF44 8005D344 00000000 */   nop
    /* 5DF48 8005D348 24090000 */  addiu      $t1, $zero, 0x0
  .L8005D34C:
    /* 5DF4C 8005D34C 3C018015 */  lui        $at, %hi(__osRdb_IP6_CurSend)
    /* 5DF50 8005D350 AC29F348 */  sw         $t1, %lo(__osRdb_IP6_CurSend)($at)
  .L8005D354:
    /* 5DF54 8005D354 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 5DF58 8005D358 31082000 */  andi       $t0, $t0, 0x2000
    /* 5DF5C 8005D35C 1408FFFD */  bne        $zero, $t0, .L8005D354
    /* 5DF60 8005D360 00000000 */   nop
    /* 5DF64 8005D364 3C08C000 */  lui        $t0, (0xC0000000 >> 16)
    /* 5DF68 8005D368 AD0A0000 */  sw         $t2, (0xC0000000 & 0xFFFF)($t0)
  .L8005D36C:
    /* 5DF6C 8005D36C DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* 5DF70 8005D370 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* 5DF74 8005D374 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* 5DF78 8005D378 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* 5DF7C 8005D37C 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 5DF80 8005D380 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 5DF84 8005D384 00000000 */  nop
    /* 5DF88 8005D388 00000000 */  nop
    /* 5DF8C 8005D38C 00000000 */  nop
    /* 5DF90 8005D390 00000000 */  nop
    /* 5DF94 8005D394 42000018 */  eret /* handwritten instruction */
  .L8005D398:
    /* 5DF98 8005D398 03404021 */  addu       $t0, $k0, $zero
    /* 5DF9C 8005D39C 3C1A8008 */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* 5DFA0 8005D3A0 8F5A9570 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* 5DFA4 8005D3A4 DD090020 */  ld         $t1, 0x20($t0)
    /* 5DFA8 8005D3A8 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* 5DFAC 8005D3AC DD090118 */  ld         $t1, 0x118($t0)
    /* 5DFB0 8005D3B0 FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* 5DFB4 8005D3B4 DD090058 */  ld         $t1, 0x58($t0)
    /* 5DFB8 8005D3B8 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* 5DFBC 8005D3BC DD090060 */  ld         $t1, 0x60($t0)
    /* 5DFC0 8005D3C0 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 5DFC4 8005D3C4 DD090068 */  ld         $t1, 0x68($t0)
    /* 5DFC8 8005D3C8 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* 5DFCC 8005D3CC FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* 5DFD0 8005D3D0 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* 5DFD4 8005D3D4 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* 5DFD8 8005D3D8 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* 5DFDC 8005D3DC FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* 5DFE0 8005D3E0 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* 5DFE4 8005D3E4 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 5DFE8 8005D3E8 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* 5DFEC 8005D3EC FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* 5DFF0 8005D3F0 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* 5DFF4 8005D3F4 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* 5DFF8 8005D3F8 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* 5DFFC 8005D3FC FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* 5E000 8005D400 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* 5E004 8005D404 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* 5E008 8005D408 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* 5E00C 8005D40C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* 5E010 8005D410 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* 5E014 8005D414 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* 5E018 8005D418 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* 5E01C 8005D41C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* 5E020 8005D420 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* 5E024 8005D424 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* 5E028 8005D428 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* 5E02C 8005D42C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* 5E030 8005D430 00004012 */  mflo       $t0
    /* 5E034 8005D434 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* 5E038 8005D438 00004010 */  mfhi       $t0
    /* 5E03C 8005D43C FF480110 */  sd         $t0, 0x110($k0) /* handwritten instruction */
    /* 5E040 8005D440 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 5E044 8005D444 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 5E048 8005D448 11200013 */  beqz       $t1, .L8005D498
    /* 5E04C 8005D44C 00000000 */   nop
    /* 5E050 8005D450 3C088008 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 5E054 8005D454 25089550 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 5E058 8005D458 8D080000 */  lw         $t0, 0x0($t0)
    /* 5E05C 8005D45C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 5E060 8005D460 01015026 */  xor        $t2, $t0, $at
    /* 5E064 8005D464 314AFF00 */  andi       $t2, $t2, 0xFF00
    /* 5E068 8005D468 012A6025 */  or         $t4, $t1, $t2
    /* 5E06C 8005D46C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 5E070 8005D470 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 5E074 8005D474 03615824 */  and        $t3, $k1, $at
    /* 5E078 8005D478 016C5825 */  or         $t3, $t3, $t4
    /* 5E07C 8005D47C AF4B0118 */  sw         $t3, 0x118($k0) /* handwritten instruction */
    /* 5E080 8005D480 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 5E084 8005D484 01284824 */  and        $t1, $t1, $t0
    /* 5E088 8005D488 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 5E08C 8005D48C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 5E090 8005D490 0361D824 */  and        $k1, $k1, $at
    /* 5E094 8005D494 0369D825 */  or         $k1, $k1, $t1
  .L8005D498:
    /* 5E098 8005D498 3C09A430 */  lui        $t1, %hi(D_A430000C)
    /* 5E09C 8005D49C 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
    /* 5E0A0 8005D4A0 1120000B */  beqz       $t1, .L8005D4D0
    /* 5E0A4 8005D4A4 00000000 */   nop
    /* 5E0A8 8005D4A8 3C088008 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 5E0AC 8005D4AC 25089550 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 5E0B0 8005D4B0 8D080000 */  lw         $t0, 0x0($t0)
    /* 5E0B4 8005D4B4 00084402 */  srl        $t0, $t0, 16
    /* 5E0B8 8005D4B8 2401FFFF */  addiu      $at, $zero, -0x1
    /* 5E0BC 8005D4BC 01014026 */  xor        $t0, $t0, $at
    /* 5E0C0 8005D4C0 3108003F */  andi       $t0, $t0, 0x3F
    /* 5E0C4 8005D4C4 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* 5E0C8 8005D4C8 010C4024 */  and        $t0, $t0, $t4
    /* 5E0CC 8005D4CC 01284825 */  or         $t1, $t1, $t0
  .L8005D4D0:
    /* 5E0D0 8005D4D0 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* 5E0D4 8005D4D4 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* 5E0D8 8005D4D8 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* 5E0DC 8005D4DC 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* 5E0E0 8005D4E0 11000014 */  beqz       $t0, .L8005D534
    /* 5E0E4 8005D4E4 00000000 */   nop
    /* 5E0E8 8005D4E8 4448F800 */  cfc1       $t0, $31
    /* 5E0EC 8005D4EC 00000000 */  nop
    /* 5E0F0 8005D4F0 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* 5E0F4 8005D4F4 F7400130 */  sdc1       $fv0, 0x130($k0)
    /* 5E0F8 8005D4F8 F7420138 */  sdc1       $fv1, 0x138($k0)
    /* 5E0FC 8005D4FC F7440140 */  sdc1       $ft0, 0x140($k0)
    /* 5E100 8005D500 F7460148 */  sdc1       $ft1, 0x148($k0)
    /* 5E104 8005D504 F7480150 */  sdc1       $ft2, 0x150($k0)
    /* 5E108 8005D508 F74A0158 */  sdc1       $ft3, 0x158($k0)
    /* 5E10C 8005D50C F74C0160 */  sdc1       $fa0, 0x160($k0)
    /* 5E110 8005D510 F74E0168 */  sdc1       $fa1, 0x168($k0)
    /* 5E114 8005D514 F7500170 */  sdc1       $ft4, 0x170($k0)
    /* 5E118 8005D518 F7520178 */  sdc1       $ft5, 0x178($k0)
    /* 5E11C 8005D51C F7540180 */  sdc1       $fs0, 0x180($k0)
    /* 5E120 8005D520 F7560188 */  sdc1       $fs1, 0x188($k0)
    /* 5E124 8005D524 F7580190 */  sdc1       $fs2, 0x190($k0)
    /* 5E128 8005D528 F75A0198 */  sdc1       $fs3, 0x198($k0)
    /* 5E12C 8005D52C F75C01A0 */  sdc1       $fs4, 0x1A0($k0)
    /* 5E130 8005D530 F75E01A8 */  sdc1       $fs5, 0x1A8($k0)
  .L8005D534:
    /* 5E134 8005D534 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 5E138 8005D538 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* 5E13C 8005D53C 24090002 */  addiu      $t1, $zero, 0x2
    /* 5E140 8005D540 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 5E144 8005D544 3C048008 */  lui        $a0, %hi(__os_Kdebug_Pkt)
    /* 5E148 8005D548 8C84962C */  lw         $a0, %lo(__os_Kdebug_Pkt)($a0)
    /* 5E14C 8005D54C 10800006 */  beqz       $a0, .L8005D568
    /* 5E150 8005D550 00000000 */   nop
    /* 5E154 8005D554 3C018008 */  lui        $at, %hi(__os_Kdebug_Pkt)
    /* 5E158 8005D558 0C0178E2 */  jal        kdebugserver
    /* 5E15C 8005D55C AC20962C */   sw        $zero, %lo(__os_Kdebug_Pkt)($at)
    /* 5E160 8005D560 10000186 */  b          .L8005DB7C
    /* 5E164 8005D564 00000000 */   nop
  .L8005D568:
    /* 5E168 8005D568 3C048008 */  lui        $a0, %hi(__osRdb_Mesg)
    /* 5E16C 8005D56C 8C849628 */  lw         $a0, %lo(__osRdb_Mesg)($a0)
    /* 5E170 8005D570 10800005 */  beqz       $a0, .L8005D588
    /* 5E174 8005D574 00000000 */   nop
    /* 5E178 8005D578 3C018008 */  lui        $at, %hi(__osRdb_Mesg)
    /* 5E17C 8005D57C 0C017643 */  jal        send_mesg
    /* 5E180 8005D580 AC209628 */   sw        $zero, %lo(__osRdb_Mesg)($at)
    /* 5E184 8005D584 8F480120 */  lw         $t0, 0x120($k0) /* handwritten instruction */
  .L8005D588:
    /* 5E188 8005D588 3109007C */  andi       $t1, $t0, 0x7C
    /* 5E18C 8005D58C 240A0024 */  addiu      $t2, $zero, 0x24
    /* 5E190 8005D590 112A00B9 */  beq        $t1, $t2, handle_break
    /* 5E194 8005D594 00000000 */   nop
    /* 5E198 8005D598 240A002C */  addiu      $t2, $zero, 0x2C
    /* 5E19C 8005D59C 112A010A */  beq        $t1, $t2, handle_CpU
    /* 5E1A0 8005D5A0 00000000 */   nop
    /* 5E1A4 8005D5A4 240A0000 */  addiu      $t2, $zero, 0x0
    /* 5E1A8 8005D5A8 152A00CC */  bne        $t1, $t2, .L8005D8DC
    /* 5E1AC 8005D5AC 00000000 */   nop
    /* 5E1B0 8005D5B0 03688024 */  and        $s0, $k1, $t0
  .L8005D5B4:
    /* 5E1B4 8005D5B4 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* 5E1B8 8005D5B8 00095302 */  srl        $t2, $t1, 12
    /* 5E1BC 8005D5BC 15400003 */  bnez       $t2, .L8005D5CC
    /* 5E1C0 8005D5C0 00000000 */   nop
    /* 5E1C4 8005D5C4 00095202 */  srl        $t2, $t1, 8
    /* 5E1C8 8005D5C8 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L8005D5CC:
    /* 5E1CC 8005D5CC 3C018008 */  lui        $at, %hi(__osIntOffTable)
    /* 5E1D0 8005D5D0 002A0821 */  addu       $at, $at, $t2
    /* 5E1D4 8005D5D4 902AEDA0 */  lbu        $t2, %lo(__osIntOffTable)($at)
    /* 5E1D8 8005D5D8 3C018008 */  lui        $at, %hi(__osIntTable)
    /* 5E1DC 8005D5DC 002A0821 */  addu       $at, $at, $t2
    /* 5E1E0 8005D5E0 8C2AEDC0 */  lw         $t2, %lo(__osIntTable)($at)
    /* 5E1E4 8005D5E4 01400008 */  jr         $t2
    /* 5E1E8 8005D5E8 00000000 */   nop

IP6_Hdlr:
    /* 5E1EC 8005D5EC 2401DFFF */  addiu      $at, $zero, -0x2001
    /* 5E1F0 8005D5F0 1000FFF0 */  b          .L8005D5B4
    /* 5E1F4 8005D5F4 02018024 */   and       $s0, $s0, $at
    
IP7_Hdlr:
    /* 5E1F8 8005D5F8 2401BFFF */  addiu      $at, $zero, -0x4001
    /* 5E1FC 8005D5FC 1000FFED */  b          .L8005D5B4
    /* 5E200 8005D600 02018024 */   and       $s0, $s0, $at

counter:
    /* 5E204 8005D604 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* 5E208 8005D608 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* 5E20C 8005D60C 24040018 */  addiu      $a0, $zero, 0x18
    /* 5E210 8005D610 0C017643 */  jal        send_mesg
    /* 5E214 8005D614 00000000 */   nop
    /* 5E218 8005D618 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* 5E21C 8005D61C 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* 5E220 8005D620 1000FFE4 */  b          .L8005D5B4
    /* 5E224 8005D624 02018024 */   and       $s0, $s0, $at

cart:
    /* 5E228 8005D628 24040010 */  addiu      $a0, $zero, 0x10
    /* 5E22C 8005D62C 2401F7FF */  addiu      $at, $zero, -0x801
    /* 5E230 8005D630 02018024 */  and        $s0, $s0, $at
    /* 5E234 8005D634 3C1D800C */  lui        $sp, %hi(leoDiskStack)
    /* 5E238 8005D638 27BDDFB0 */  addiu      $sp, $sp, %lo(leoDiskStack)
    /* 5E23C 8005D63C 27BD0FF0 */  addiu      $sp, $sp, 0xFF0
    /* 5E240 8005D640 240A0004 */  addiu      $t2, $zero, 0x4
    /* 5E244 8005D644 3C018008 */  lui        $at, %hi(__osHwIntTable)
    /* 5E248 8005D648 002A0821 */  addu       $at, $at, $t2
    /* 5E24C 8005D64C 8C2A9610 */  lw         $t2, %lo(__osHwIntTable)($at)
    /* 5E250 8005D650 11400007 */  beqz       $t2, .L8005D670
    /* 5E254 8005D654 00000000 */   nop
    /* 5E258 8005D658 0140F809 */  jalr       $t2
    /* 5E25C 8005D65C 00000000 */   nop
    /* 5E260 8005D660 10400003 */  beqz       $v0, .L8005D670
    /* 5E264 8005D664 24040010 */   addiu     $a0, $zero, 0x10
    /* 5E268 8005D668 10000089 */  b          redispatch
    /* 5E26C 8005D66C 00000000 */   nop
  .L8005D670:
    /* 5E270 8005D670 0C017643 */  jal        send_mesg
    /* 5E274 8005D674 00000000 */   nop
    /* 5E278 8005D678 1000FFCE */  b          .L8005D5B4
    /* 5E27C 8005D67C 00000000 */   nop

rcp:
    /* 5E280 8005D680 3C11A430 */  lui        $s1, %hi(D_A4300008)
    /* 5E284 8005D684 8E310008 */  lw         $s1, %lo(D_A4300008)($s1)
    /* 5E288 8005D688 3C088008 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 5E28C 8005D68C 25089550 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 5E290 8005D690 8D080000 */  lw         $t0, 0x0($t0)
    /* 5E294 8005D694 00084402 */  srl        $t0, $t0, 16
    /* 5E298 8005D698 02288824 */  and        $s1, $s1, $t0
    /* 5E29C 8005D69C 32290001 */  andi       $t1, $s1, 0x1
    /* 5E2A0 8005D6A0 11200014 */  beqz       $t1, vi
    /* 5E2A4 8005D6A4 00000000 */   nop
    /* 5E2A8 8005D6A8 3231003E */  andi       $s1, $s1, 0x3E
    /* 5E2AC 8005D6AC 3C0CA404 */  lui        $t4, %hi(D_A4040010)
    /* 5E2B0 8005D6B0 8D8C0010 */  lw         $t4, %lo(D_A4040010)($t4)
    /* 5E2B4 8005D6B4 34098008 */  ori        $t1, $zero, 0x8008
    /* 5E2B8 8005D6B8 3C01A404 */  lui        $at, %hi(D_A4040010)
    /* 5E2BC 8005D6BC AC290010 */  sw         $t1, %lo(D_A4040010)($at)
    /* 5E2C0 8005D6C0 318C0300 */  andi       $t4, $t4, 0x300
    /* 5E2C4 8005D6C4 11800007 */  beqz       $t4, sp_other_break
    /* 5E2C8 8005D6C8 00000000 */   nop
    /* 5E2CC 8005D6CC 0C017643 */  jal        send_mesg
    /* 5E2D0 8005D6D0 24040020 */   addiu     $a0, $zero, 0x20
    /* 5E2D4 8005D6D4 1220003A */  beqz       $s1, NoMoreRcpInts
    /* 5E2D8 8005D6D8 00000000 */   nop
    /* 5E2DC 8005D6DC 10000005 */  b          vi
    /* 5E2E0 8005D6E0 00000000 */   nop

sp_other_break:
    /* 5E2E4 8005D6E4 0C017643 */  jal        send_mesg
    /* 5E2E8 8005D6E8 24040058 */   addiu     $a0, $zero, 0x58
    /* 5E2EC 8005D6EC 12200034 */  beqz       $s1, NoMoreRcpInts
    /* 5E2F0 8005D6F0 00000000 */   nop

vi:
    /* 5E2F4 8005D6F4 32290008 */  andi       $t1, $s1, 0x8
    /* 5E2F8 8005D6F8 11200008 */  beqz       $t1, ai
    /* 5E2FC 8005D6FC 00000000 */   nop
    /* 5E300 8005D700 32310037 */  andi       $s1, $s1, 0x37
    /* 5E304 8005D704 3C01A440 */  lui        $at, %hi(D_A4400010)
    /* 5E308 8005D708 AC200010 */  sw         $zero, %lo(D_A4400010)($at)
    /* 5E30C 8005D70C 0C017643 */  jal        send_mesg
    /* 5E310 8005D710 24040038 */   addiu     $a0, $zero, 0x38
    /* 5E314 8005D714 1220002A */  beqz       $s1, NoMoreRcpInts
    /* 5E318 8005D718 00000000 */   nop

ai:
    /* 5E31C 8005D71C 32290004 */  andi       $t1, $s1, 0x4
    /* 5E320 8005D720 11200009 */  beqz       $t1, si
    /* 5E324 8005D724 00000000 */   nop
    /* 5E328 8005D728 3231003B */  andi       $s1, $s1, 0x3B
    /* 5E32C 8005D72C 24090001 */  addiu      $t1, $zero, 0x1
    /* 5E330 8005D730 3C01A450 */  lui        $at, %hi(D_A450000C)
    /* 5E334 8005D734 AC29000C */  sw         $t1, %lo(D_A450000C)($at)
    /* 5E338 8005D738 0C017643 */  jal        send_mesg
    /* 5E33C 8005D73C 24040030 */   addiu     $a0, $zero, 0x30
    /* 5E340 8005D740 1220001F */  beqz       $s1, NoMoreRcpInts
    /* 5E344 8005D744 00000000 */   nop

si:
    /* 5E348 8005D748 32290002 */  andi       $t1, $s1, 0x2
    /* 5E34C 8005D74C 11200008 */  beqz       $t1, pi
    /* 5E350 8005D750 00000000 */   nop
    /* 5E354 8005D754 3231003D */  andi       $s1, $s1, 0x3D
    /* 5E358 8005D758 3C01A480 */  lui        $at, %hi(D_A4800018)
    /* 5E35C 8005D75C AC200018 */  sw         $zero, %lo(D_A4800018)($at)
    /* 5E360 8005D760 0C017643 */  jal        send_mesg
    /* 5E364 8005D764 24040028 */   addiu     $a0, $zero, 0x28
    /* 5E368 8005D768 12200015 */  beqz       $s1, NoMoreRcpInts
    /* 5E36C 8005D76C 00000000 */   nop

pi:
    /* 5E370 8005D770 32290010 */  andi       $t1, $s1, 0x10
    /* 5E374 8005D774 11200009 */  beqz       $t1, dp
    /* 5E378 8005D778 00000000 */   nop
    /* 5E37C 8005D77C 3231002F */  andi       $s1, $s1, 0x2F
    /* 5E380 8005D780 24090002 */  addiu      $t1, $zero, 0x2
    /* 5E384 8005D784 3C01A460 */  lui        $at, %hi(D_A4600010)
    /* 5E388 8005D788 AC290010 */  sw         $t1, %lo(D_A4600010)($at)
    /* 5E38C 8005D78C 0C017643 */  jal        send_mesg
    /* 5E390 8005D790 24040040 */   addiu     $a0, $zero, 0x40
    /* 5E394 8005D794 1220000A */  beqz       $s1, NoMoreRcpInts
    /* 5E398 8005D798 00000000 */   nop

dp:
    /* 5E39C 8005D79C 32290020 */  andi       $t1, $s1, 0x20
    /* 5E3A0 8005D7A0 11200007 */  beqz       $t1, NoMoreRcpInts
    /* 5E3A4 8005D7A4 00000000 */   nop
    /* 5E3A8 8005D7A8 3231001F */  andi       $s1, $s1, 0x1F
    /* 5E3AC 8005D7AC 24090800 */  addiu      $t1, $zero, 0x800
    /* 5E3B0 8005D7B0 3C01A430 */  lui        $at, %hi(D_A4300000)
    /* 5E3B4 8005D7B4 AC290000 */  sw         $t1, %lo(D_A4300000)($at)
    /* 5E3B8 8005D7B8 0C017643 */  jal        send_mesg
    /* 5E3BC 8005D7BC 24040048 */   addiu     $a0, $zero, 0x48

NoMoreRcpInts:
    /* 5E3C0 8005D7C0 2401FBFF */  addiu      $at, $zero, -0x401
    /* 5E3C4 8005D7C4 1000FF7B */  b          .L8005D5B4
    /* 5E3C8 8005D7C8 02018024 */   and       $s0, $s0, $at

prenmi:
    /* 5E3CC 8005D7CC 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 5E3D0 8005D7D0 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 5E3D4 8005D7D4 0361D824 */  and        $k1, $k1, $at
    /* 5E3D8 8005D7D8 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 5E3DC 8005D7DC 3C098008 */  lui        $t1, %hi(__osShutdown)
    /* 5E3E0 8005D7E0 2529954C */  addiu      $t1, $t1, %lo(__osShutdown)
    /* 5E3E4 8005D7E4 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 5E3E8 8005D7E8 11400004 */  beqz       $t2, firstnmi
    /* 5E3EC 8005D7EC 00000000 */   nop
    /* 5E3F0 8005D7F0 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 5E3F4 8005D7F4 10000026 */  b          redispatch
    /* 5E3F8 8005D7F8 02018024 */   and       $s0, $s0, $at

firstnmi:
    /* 5E3FC 8005D7FC 240A0001 */  addiu      $t2, $zero, 0x1
    /* 5E400 8005D800 AD2A0000 */  sw         $t2, 0x0($t1)
    /* 5E404 8005D804 0C017643 */  jal        send_mesg
    /* 5E408 8005D808 24040070 */   addiu     $a0, $zero, 0x70
    /* 5E40C 8005D80C 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 5E410 8005D810 02018024 */  and        $s0, $s0, $at
    /* 5E414 8005D814 3C0A8008 */  lui        $t2, %hi(__osRunQueue)
    /* 5E418 8005D818 8D4A9568 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 5E41C 8005D81C 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* 5E420 8005D820 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 5E424 8005D824 0361D824 */  and        $k1, $k1, $at
    /* 5E428 8005D828 10000019 */  b          redispatch
    /* 5E42C 8005D82C AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */

sw2:
    /* 5E430 8005D830 2401FDFF */  addiu      $at, $zero, -0x201
    /* 5E434 8005D834 01014024 */  and        $t0, $t0, $at
    /* 5E438 8005D838 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 5E43C 8005D83C 24040008 */  addiu      $a0, $zero, 0x8
    /* 5E440 8005D840 0C017643 */  jal        send_mesg
    /* 5E444 8005D844 00000000 */   nop
    /* 5E448 8005D848 2401FDFF */  addiu      $at, $zero, -0x201
    /* 5E44C 8005D84C 1000FF59 */  b          .L8005D5B4
    /* 5E450 8005D850 02018024 */   and       $s0, $s0, $at

sw1:
    /* 5E454 8005D854 2401FEFF */  addiu      $at, $zero, -0x101
    /* 5E458 8005D858 01014024 */  and        $t0, $t0, $at
    /* 5E45C 8005D85C 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 5E460 8005D860 24040000 */  addiu      $a0, $zero, 0x0
    /* 5E464 8005D864 0C017643 */  jal        send_mesg
    /* 5E468 8005D868 00000000 */   nop
    /* 5E46C 8005D86C 2401FEFF */  addiu      $at, $zero, -0x101
    /* 5E470 8005D870 1000FF50 */  b          .L8005D5B4
    /* 5E474 8005D874 02018024 */   and       $s0, $s0, $at

handle_break:
    /* 5E478 8005D878 24090001 */  addiu      $t1, $zero, 0x1
    /* 5E47C 8005D87C A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 5E480 8005D880 0C017643 */  jal        send_mesg
    /* 5E484 8005D884 24040050 */   addiu     $a0, $zero, 0x50
    /* 5E488 8005D888 10000001 */  b          redispatch
    /* 5E48C 8005D88C 00000000 */   nop

redispatch:
    /* 5E490 8005D890 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* 5E494 8005D894 3C0A8008 */  lui        $t2, %hi(__osRunQueue)
    /* 5E498 8005D898 8D4A9568 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 5E49C 8005D89C 8D4B0004 */  lw         $t3, 0x4($t2)
    /* 5E4A0 8005D8A0 012B082A */  slt        $at, $t1, $t3
    /* 5E4A4 8005D8A4 10200007 */  beqz       $at, .L8005D8C4
    /* 5E4A8 8005D8A8 00000000 */   nop
    /* 5E4AC 8005D8AC 03402821 */  addu       $a1, $k0, $zero
    /* 5E4B0 8005D8B0 3C048008 */  lui        $a0, %hi(__osRunQueue)
    /* 5E4B4 8005D8B4 0C0176C1 */  jal        __osEnqueueThread
    /* 5E4B8 8005D8B8 24849568 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 5E4BC 8005D8BC 080176D7 */  j          __osDispatchThread
    /* 5E4C0 8005D8C0 00000000 */   nop
  .L8005D8C4:
    /* 5E4C4 8005D8C4 3C098008 */  lui        $t1, %hi(__osRunQueue)
    /* 5E4C8 8005D8C8 25299568 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* 5E4CC 8005D8CC 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 5E4D0 8005D8D0 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* 5E4D4 8005D8D4 080176D7 */  j          __osDispatchThread
    /* 5E4D8 8005D8D8 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L8005D8DC:
    /* 5E4DC 8005D8DC 3C018008 */  lui        $at, %hi(__osFaultedThread)
    /* 5E4E0 8005D8E0 AC3A9574 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
    /* 5E4E4 8005D8E4 24090001 */  addiu      $t1, $zero, 0x1
    /* 5E4E8 8005D8E8 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 5E4EC 8005D8EC 24090002 */  addiu      $t1, $zero, 0x2
    /* 5E4F0 8005D8F0 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 5E4F4 8005D8F4 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* 5E4F8 8005D8F8 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* 5E4FC 8005D8FC 0C017643 */  jal        send_mesg
    /* 5E500 8005D900 24040060 */   addiu     $a0, $zero, 0x60
    /* 5E504 8005D904 080176D7 */  j          __osDispatchThread
    /* 5E508 8005D908 00000000 */   nop
endlabel __osException


glabel send_mesg
    /* 5E50C 8005D90C 03E09021 */  addu       $s2, $ra, $zero
    /* 5E510 8005D910 3C0A8015 */  lui        $t2, %hi(__osEventStateTab)
    /* 5E514 8005D914 254A6B18 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* 5E518 8005D918 01445021 */  addu       $t2, $t2, $a0
    /* 5E51C 8005D91C 8D490000 */  lw         $t1, 0x0($t2)
    /* 5E520 8005D920 11200027 */  beqz       $t1, .L8005D9C0
    /* 5E524 8005D924 00000000 */   nop
    /* 5E528 8005D928 8D2B0008 */  lw         $t3, 0x8($t1)
    /* 5E52C 8005D92C 8D2C0010 */  lw         $t4, 0x10($t1)
    /* 5E530 8005D930 016C082A */  slt        $at, $t3, $t4
    /* 5E534 8005D934 10200022 */  beqz       $at, .L8005D9C0
    /* 5E538 8005D938 00000000 */   nop
    /* 5E53C 8005D93C 8D2D000C */  lw         $t5, 0xC($t1)
    /* 5E540 8005D940 01AB6821 */  addu       $t5, $t5, $t3
    /* 5E544 8005D944 01AC001A */  div        $zero, $t5, $t4
    /* 5E548 8005D948 15800002 */  bnez       $t4, .L8005D954
    /* 5E54C 8005D94C 00000000 */   nop
    /* 5E550 8005D950 0007000D */  break      7
  .L8005D954:
    /* 5E554 8005D954 2401FFFF */  addiu      $at, $zero, -0x1
    /* 5E558 8005D958 15810004 */  bne        $t4, $at, .L8005D96C
    /* 5E55C 8005D95C 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 5E560 8005D960 15A10002 */  bne        $t5, $at, .L8005D96C
    /* 5E564 8005D964 00000000 */   nop
    /* 5E568 8005D968 0006000D */  break      6
  .L8005D96C:
    /* 5E56C 8005D96C 00006810 */  mfhi       $t5
    /* 5E570 8005D970 8D2C0014 */  lw         $t4, 0x14($t1)
    /* 5E574 8005D974 24010004 */  addiu      $at, $zero, 0x4
    /* 5E578 8005D978 01A10018 */  mult       $t5, $at
    /* 5E57C 8005D97C 00006812 */  mflo       $t5
    /* 5E580 8005D980 018D6021 */  addu       $t4, $t4, $t5
    /* 5E584 8005D984 8D4D0004 */  lw         $t5, 0x4($t2)
    /* 5E588 8005D988 AD8D0000 */  sw         $t5, 0x0($t4)
    /* 5E58C 8005D98C 256A0001 */  addiu      $t2, $t3, 0x1
    /* 5E590 8005D990 AD2A0008 */  sw         $t2, 0x8($t1)
    /* 5E594 8005D994 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 5E598 8005D998 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 5E59C 8005D99C 11600008 */  beqz       $t3, .L8005D9C0
    /* 5E5A0 8005D9A0 00000000 */   nop
    /* 5E5A4 8005D9A4 0C0176D3 */  jal        __osPopThread
    /* 5E5A8 8005D9A8 01202021 */   addu      $a0, $t1, $zero
    /* 5E5AC 8005D9AC 00405021 */  addu       $t2, $v0, $zero
    /* 5E5B0 8005D9B0 01402821 */  addu       $a1, $t2, $zero
    /* 5E5B4 8005D9B4 3C048008 */  lui        $a0, %hi(__osRunQueue)
    /* 5E5B8 8005D9B8 0C0176C1 */  jal        __osEnqueueThread
    /* 5E5BC 8005D9BC 24849568 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .L8005D9C0:
    /* 5E5C0 8005D9C0 02400008 */  jr         $s2
    /* 5E5C4 8005D9C4 00000000 */   nop
endlabel send_mesg

/* Handwritten function */

glabel handle_CpU
    /* 5E5C8 8005D9C8 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* 5E5CC 8005D9CC 01014824 */  and        $t1, $t0, $at
    /* 5E5D0 8005D9D0 00094F02 */  srl        $t1, $t1, 28
    /* 5E5D4 8005D9D4 240A0001 */  addiu      $t2, $zero, 0x1
    /* 5E5D8 8005D9D8 152AFFC0 */  bne        $t1, $t2, .L8005D8DC
    /* 5E5DC 8005D9DC 00000000 */   nop
    /* 5E5E0 8005D9E0 24090001 */  addiu      $t1, $zero, 0x1
    /* 5E5E4 8005D9E4 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* 5E5E8 8005D9E8 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 5E5EC 8005D9EC 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* 5E5F0 8005D9F0 0361D825 */  or         $k1, $k1, $at
    /* 5E5F4 8005D9F4 1000FFB3 */  b          .L8005D8C4
    /* 5E5F8 8005D9F8 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */
endlabel handle_CpU

/* Handwritten function */

glabel __osEnqueueAndYield
    /* 5E5FC 8005D9FC 3C058008 */  lui        $a1, %hi(__osRunningThread)
    /* 5E600 8005DA00 8CA59570 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* 5E604 8005DA04 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 5E608 8005DA08 35080002 */  ori        $t0, $t0, 0x2
    /* 5E60C 8005DA0C ACA80118 */  sw         $t0, 0x118($a1)
    /* 5E610 8005DA10 FCB00098 */  sd         $s0, 0x98($a1)
    /* 5E614 8005DA14 FCB100A0 */  sd         $s1, 0xA0($a1)
    /* 5E618 8005DA18 FCB200A8 */  sd         $s2, 0xA8($a1)
    /* 5E61C 8005DA1C FCB300B0 */  sd         $s3, 0xB0($a1)
    /* 5E620 8005DA20 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* 5E624 8005DA24 FCB500C0 */  sd         $s5, 0xC0($a1)
    /* 5E628 8005DA28 FCB600C8 */  sd         $s6, 0xC8($a1)
    /* 5E62C 8005DA2C FCB700D0 */  sd         $s7, 0xD0($a1)
    /* 5E630 8005DA30 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* 5E634 8005DA34 FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* 5E638 8005DA38 FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* 5E63C 8005DA3C FCBF0100 */  sd         $ra, 0x100($a1)
    /* 5E640 8005DA40 ACBF011C */  sw         $ra, 0x11C($a1)
    /* 5E644 8005DA44 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* 5E648 8005DA48 1360000A */  beqz       $k1, .L8005DA74 /* handwritten instruction */
    /* 5E64C 8005DA4C 00000000 */   nop
    /* 5E650 8005DA50 445BF800 */  cfc1       $k1, $31
    /* 5E654 8005DA54 00000000 */  nop
    /* 5E658 8005DA58 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
    /* 5E65C 8005DA5C F4B40180 */  sdc1       $fs0, 0x180($a1)
    /* 5E660 8005DA60 F4B60188 */  sdc1       $fs1, 0x188($a1)
    /* 5E664 8005DA64 F4B80190 */  sdc1       $fs2, 0x190($a1)
    /* 5E668 8005DA68 F4BA0198 */  sdc1       $fs3, 0x198($a1)
    /* 5E66C 8005DA6C F4BC01A0 */  sdc1       $fs4, 0x1A0($a1)
    /* 5E670 8005DA70 F4BE01A8 */  sdc1       $fs5, 0x1A8($a1)
  .L8005DA74:
    /* 5E674 8005DA74 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* 5E678 8005DA78 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 5E67C 8005DA7C 1120000D */  beqz       $t1, .L8005DAB4
    /* 5E680 8005DA80 00000000 */   nop
    /* 5E684 8005DA84 3C088008 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 5E688 8005DA88 25089550 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 5E68C 8005DA8C 8D080000 */  lw         $t0, 0x0($t0)
    /* 5E690 8005DA90 2401FFFF */  addiu      $at, $zero, -0x1
    /* 5E694 8005DA94 01014026 */  xor        $t0, $t0, $at
    /* 5E698 8005DA98 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 5E69C 8005DA9C 01284825 */  or         $t1, $t1, $t0
    /* 5E6A0 8005DAA0 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 5E6A4 8005DAA4 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 5E6A8 8005DAA8 0361D824 */  and        $k1, $k1, $at
    /* 5E6AC 8005DAAC 0369D825 */  or         $k1, $k1, $t1
    /* 5E6B0 8005DAB0 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .L8005DAB4:
    /* 5E6B4 8005DAB4 3C1BA430 */  lui        $k1, %hi(D_A430000C) /* handwritten instruction */
    /* 5E6B8 8005DAB8 8F7B000C */  lw         $k1, %lo(D_A430000C)($k1) /* handwritten instruction */
    /* 5E6BC 8005DABC 1360000B */  beqz       $k1, .L8005DAEC /* handwritten instruction */
    /* 5E6C0 8005DAC0 00000000 */   nop
    /* 5E6C4 8005DAC4 3C1A8008 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* 5E6C8 8005DAC8 275A9550 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* 5E6CC 8005DACC 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 5E6D0 8005DAD0 001AD402 */  srl        $k0, $k0, 16
    /* 5E6D4 8005DAD4 2401FFFF */  addiu      $at, $zero, -0x1
    /* 5E6D8 8005DAD8 0341D026 */  xor        $k0, $k0, $at
    /* 5E6DC 8005DADC 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* 5E6E0 8005DAE0 8CA80128 */  lw         $t0, 0x128($a1)
    /* 5E6E4 8005DAE4 0348D024 */  and        $k0, $k0, $t0
    /* 5E6E8 8005DAE8 037AD825 */  or         $k1, $k1, $k0
  .L8005DAEC:
    /* 5E6EC 8005DAEC 10800003 */  beqz       $a0, .L8005DAFC
    /* 5E6F0 8005DAF0 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* 5E6F4 8005DAF4 0C0176C1 */  jal        __osEnqueueThread
    /* 5E6F8 8005DAF8 00000000 */   nop
  .L8005DAFC:
    /* 5E6FC 8005DAFC 080176D7 */  j          __osDispatchThread
    /* 5E700 8005DB00 00000000 */   nop
endlabel __osEnqueueAndYield


glabel __osEnqueueThread
    /* 5E704 8005DB04 0080C821 */  addu       $t9, $a0, $zero
    /* 5E708 8005DB08 8C980000 */  lw         $t8, 0x0($a0)
    /* 5E70C 8005DB0C 8CAF0004 */  lw         $t7, 0x4($a1)
    /* 5E710 8005DB10 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 5E714 8005DB14 01CF082A */  slt        $at, $t6, $t7
    /* 5E718 8005DB18 14200007 */  bnez       $at, .L8005DB38
    /* 5E71C 8005DB1C 00000000 */   nop
  .L8005DB20:
    /* 5E720 8005DB20 0300C821 */  addu       $t9, $t8, $zero
    /* 5E724 8005DB24 8F180000 */  lw         $t8, 0x0($t8)
    /* 5E728 8005DB28 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 5E72C 8005DB2C 01CF082A */  slt        $at, $t6, $t7
    /* 5E730 8005DB30 1020FFFB */  beqz       $at, .L8005DB20
    /* 5E734 8005DB34 00000000 */   nop
  .L8005DB38:
    /* 5E738 8005DB38 8F380000 */  lw         $t8, 0x0($t9)
    /* 5E73C 8005DB3C ACB80000 */  sw         $t8, 0x0($a1)
    /* 5E740 8005DB40 AF250000 */  sw         $a1, 0x0($t9)
    /* 5E744 8005DB44 03E00008 */  jr         $ra
    /* 5E748 8005DB48 ACA40008 */   sw        $a0, 0x8($a1)
endlabel __osEnqueueThread


glabel __osPopThread
    /* 5E74C 8005DB4C 8C820000 */  lw         $v0, 0x0($a0)
    /* 5E750 8005DB50 8C590000 */  lw         $t9, 0x0($v0)
    /* 5E754 8005DB54 03E00008 */  jr         $ra
    /* 5E758 8005DB58 AC990000 */   sw        $t9, 0x0($a0)
endlabel __osPopThread

/* Handwritten function */

glabel __osDispatchThread
    /* 5E75C 8005DB5C 3C048008 */  lui        $a0, %hi(__osRunQueue)
    /* 5E760 8005DB60 0C0176D3 */  jal        __osPopThread
    /* 5E764 8005DB64 24849568 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 5E768 8005DB68 3C018008 */  lui        $at, %hi(__osRunningThread)
    /* 5E76C 8005DB6C AC229570 */  sw         $v0, %lo(__osRunningThread)($at)
    /* 5E770 8005DB70 24080004 */  addiu      $t0, $zero, 0x4
    /* 5E774 8005DB74 A4480010 */  sh         $t0, 0x10($v0)
    /* 5E778 8005DB78 0040D021 */  addu       $k0, $v0, $zero
  .L8005DB7C:
    /* 5E77C 8005DB7C 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 5E780 8005DB80 3C088008 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 5E784 8005DB84 25089550 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 5E788 8005DB88 8D080000 */  lw         $t0, 0x0($t0)
    /* 5E78C 8005DB8C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 5E790 8005DB90 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 5E794 8005DB94 01284824 */  and        $t1, $t1, $t0
    /* 5E798 8005DB98 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 5E79C 8005DB9C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 5E7A0 8005DBA0 0361D824 */  and        $k1, $k1, $at
    /* 5E7A4 8005DBA4 0369D825 */  or         $k1, $k1, $t1
    /* 5E7A8 8005DBA8 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 5E7AC 8005DBAC DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* 5E7B0 8005DBB0 DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* 5E7B4 8005DBB4 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* 5E7B8 8005DBB8 DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* 5E7BC 8005DBBC DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* 5E7C0 8005DBC0 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* 5E7C4 8005DBC4 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* 5E7C8 8005DBC8 DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* 5E7CC 8005DBCC DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* 5E7D0 8005DBD0 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* 5E7D4 8005DBD4 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* 5E7D8 8005DBD8 DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* 5E7DC 8005DBDC DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* 5E7E0 8005DBE0 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* 5E7E4 8005DBE4 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* 5E7E8 8005DBE8 DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* 5E7EC 8005DBEC DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* 5E7F0 8005DBF0 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* 5E7F4 8005DBF4 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* 5E7F8 8005DBF8 DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* 5E7FC 8005DBFC DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* 5E800 8005DC00 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* 5E804 8005DC04 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* 5E808 8005DC08 DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* 5E80C 8005DC0C DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* 5E810 8005DC10 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* 5E814 8005DC14 DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* 5E818 8005DC18 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* 5E81C 8005DC1C DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* 5E820 8005DC20 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* 5E824 8005DC24 03600013 */  mtlo       $k1
    /* 5E828 8005DC28 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* 5E82C 8005DC2C 03600011 */  mthi       $k1
    /* 5E830 8005DC30 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* 5E834 8005DC34 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* 5E838 8005DC38 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* 5E83C 8005DC3C 13600013 */  beqz       $k1, .L8005DC8C /* handwritten instruction */
    /* 5E840 8005DC40 00000000 */   nop
    /* 5E844 8005DC44 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* 5E848 8005DC48 44DBF800 */  ctc1       $k1, $31
    /* 5E84C 8005DC4C D7400130 */  ldc1       $fv0, 0x130($k0)
    /* 5E850 8005DC50 D7420138 */  ldc1       $fv1, 0x138($k0)
    /* 5E854 8005DC54 D7440140 */  ldc1       $ft0, 0x140($k0)
    /* 5E858 8005DC58 D7460148 */  ldc1       $ft1, 0x148($k0)
    /* 5E85C 8005DC5C D7480150 */  ldc1       $ft2, 0x150($k0)
    /* 5E860 8005DC60 D74A0158 */  ldc1       $ft3, 0x158($k0)
    /* 5E864 8005DC64 D74C0160 */  ldc1       $fa0, 0x160($k0)
    /* 5E868 8005DC68 D74E0168 */  ldc1       $fa1, 0x168($k0)
    /* 5E86C 8005DC6C D7500170 */  ldc1       $ft4, 0x170($k0)
    /* 5E870 8005DC70 D7520178 */  ldc1       $ft5, 0x178($k0)
    /* 5E874 8005DC74 D7540180 */  ldc1       $fs0, 0x180($k0)
    /* 5E878 8005DC78 D7560188 */  ldc1       $fs1, 0x188($k0)
    /* 5E87C 8005DC7C D7580190 */  ldc1       $fs2, 0x190($k0)
    /* 5E880 8005DC80 D75A0198 */  ldc1       $fs3, 0x198($k0)
    /* 5E884 8005DC84 D75C01A0 */  ldc1       $fs4, 0x1A0($k0)
    /* 5E888 8005DC88 D75E01A8 */  ldc1       $fs5, 0x1A8($k0)
  .L8005DC8C:
    /* 5E88C 8005DC8C 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* 5E890 8005DC90 3C1A8008 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* 5E894 8005DC94 275A9550 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* 5E898 8005DC98 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 5E89C 8005DC9C 001AD402 */  srl        $k0, $k0, 16
    /* 5E8A0 8005DCA0 037AD824 */  and        $k1, $k1, $k0
    /* 5E8A4 8005DCA4 001BD840 */  sll        $k1, $k1, 1
    /* 5E8A8 8005DCA8 3C1A8008 */  lui        $k0, %hi(__osRcpImTable) /* handwritten instruction */
    /* 5E8AC 8005DCAC 275AEE10 */  addiu      $k0, $k0, %lo(__osRcpImTable) /* handwritten instruction */
    /* 5E8B0 8005DCB0 037AD821 */  addu       $k1, $k1, $k0
    /* 5E8B4 8005DCB4 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* 5E8B8 8005DCB8 3C1AA430 */  lui        $k0, (0xA430000C >> 16) /* handwritten instruction */
    /* 5E8BC 8005DCBC 375A000C */  ori        $k0, $k0, (0xA430000C & 0xFFFF) /* handwritten instruction */
    /* 5E8C0 8005DCC0 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* 5E8C4 8005DCC4 00000000 */  nop
    /* 5E8C8 8005DCC8 00000000 */  nop
    /* 5E8CC 8005DCCC 00000000 */  nop
    /* 5E8D0 8005DCD0 00000000 */  nop
    /* 5E8D4 8005DCD4 42000018 */  eret /* handwritten instruction */
endlabel __osDispatchThread


glabel __osCleanupThread
    /* 5E8D8 8005DCD8 00002021 */  addu       $a0, $zero, $zero
    /* 5E8DC 8005DCDC 0C0177C8 */  jal        osDestroyThread
    /* 5E8E0 8005DCE0 00000000 */   nop
endlabel __osCleanupThread
    /* 5E8E4 8005DCE4 00000000 */  nop
    /* 5E8E8 8005DCE8 00000000 */  nop
    /* 5E8EC 8005DCEC 00000000 */  nop
