.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.1 */

glabel osMapTLBRdb
    /* 5EAC0 8005DEC0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 5EAC4 8005DEC4 2409001F */  addiu      $t1, $zero, 0x1F
    /* 5EAC8 8005DEC8 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 5EACC 8005DECC 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* 5EAD0 8005DED0 240A0017 */  addiu      $t2, $zero, 0x17
    /* 5EAD4 8005DED4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* 5EAD8 8005DED8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 5EADC 8005DEDC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* 5EAE0 8005DEE0 00095982 */  srl        $t3, $t1, 6
    /* 5EAE4 8005DEE4 016A5825 */  or         $t3, $t3, $t2
    /* 5EAE8 8005DEE8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 5EAEC 8005DEEC 24090001 */  addiu      $t1, $zero, 0x1
    /* 5EAF0 8005DEF0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* 5EAF4 8005DEF4 00000000 */  nop
    /* 5EAF8 8005DEF8 42000002 */  tlbwi /* handwritten instruction */
    /* 5EAFC 8005DEFC 00000000 */  nop
    /* 5EB00 8005DF00 00000000 */  nop
    /* 5EB04 8005DF04 00000000 */  nop
    /* 5EB08 8005DF08 00000000 */  nop
    /* 5EB0C 8005DF0C 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 5EB10 8005DF10 03E00008 */  jr         $ra
    /* 5EB14 8005DF14 00000000 */   nop
endlabel osMapTLBRdb
    /* 5EB18 8005DF18 00000000 */  nop
    /* 5EB1C 8005DF1C 00000000 */  nop
