.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.1 */


glabel __osSetFpcCsr
    /* 5EAA0 8005DEA0 4442F800 */  cfc1       $v0, $31
    /* 5EAA4 8005DEA4 44C4F800 */  ctc1       $a0, $31
    /* 5EAA8 8005DEA8 03E00008 */  jr         $ra
    /* 5EAAC 8005DEAC 00000000 */   nop
endlabel __osSetFpcCsr
