#ifndef SIGNAL_H_
#define SIGNAL_H_

#include "types/Instance.h"

int func_8004AADC(void);
int GetLevelIndexFromId(const char* targetLevelId);
short GetRedRemotesForLevel(unsigned int levelIndex);
void func_8004C43C();
int func_8004C66C(void);
void SIGNAL_HandleSignal(Instance* instance, void* signal, int arg2);
void COLLIDE_HandleSignal(Instance* instance, void* signal, int numSignals, int arg3);

int SIGNAL_HideObject(Instance* instance, void* signal);
int SIGNAL_UnhideObject(Instance* instance, void* signal);
int SIGNAL_Timer(Instance* instance, void* signal);
int SIGNAL_GotoFrame(Instance* instance, void* signal);
int SIGNAL_ChangeModel(Instance* instance, void* signal);
int SIGNAL_StartAniTex(Instance* instance, void* signal);
int SIGNAL_StopAniTex(Instance* instance, void* signal);
int SIGNAL_StartSpline(Instance* instance, void* signal);
int SIGNAL_StopSpline(Instance* instance, void* signal);
int SIGNAL_DeathZ(Instance* instance, void* signal);
int SIGNAL_DSignal(Instance* instance, void* signal);
int SIGNAL_GSignal(Instance* instance, void* signal);
int SIGNAL_LightGroup(Instance* instance, void* signal);
int SIGNAL_CameraAdjust(Instance* instance, void* signal);
int SIGNAL_CameraMode(Instance* instance, void* signal);
int SIGNAL_Camera(Instance* instance, void* signal);
int SIGNAL_CameraTimer(Instance* instance, void* signal);
int SIGNAL_CameraSmooth(Instance* instance, void* signal);
int SIGNAL_CameraValue(Instance* instance, void* signal);
int SIGNAL_CameraLock(Instance* instance, void* signal);
int SIGNAL_CameraUnlock(Instance* instance, void* signal);
int SIGNAL_CameraSave(Instance* instance, void* signal);
int SIGNAL_CameraRestore(Instance* instance, void* signal);
int SIGNAL_Teleport(Instance* instance, void* signal);
int SIGNAL_FarPlane(Instance* instance, void* signal);
int SIGNAL_SoundStartSequence(Instance* instance, void* signal);
int SIGNAL_SoundStopSlot(Instance* instance, void* signal);
int SIGNAL_SoundPauseSlot(Instance* instance, void* signal);
int SIGNAL_SoundResumeSlot(Instance* instance, void* signal);
int SIGNAL_SoundMuteChannel(Instance* instance, void* signal);
int SIGNAL_SoundUnmuteChannel(Instance* instance, void* signal);
int SIGNAL_Times(Instance* instance, void* signal);
int SIGNAL_Freeze(Instance* instance, void* signal);
int SIGNAL_UnFreeze(Instance* instance, void* signal);
int SIGNAL_FreezeAll(Instance* instance, void* signal);
int SIGNAL_UnfreezeAll(Instance* instance, void* signal);
int SIGNAL_HideBG(Instance* instance, void* signal);
int SIGNAL_UnhideBG(Instance* instance, void* signal);
int SIGNAL_HideBGObject(Instance* instance, void* signal);
int SIGNAL_UnhideBGObject(Instance* instance, void* signal);
int SIGNAL_Mirror(Instance* instance, void* signal);
int SIGNAL_Unmirror(Instance* instance, void* signal);
int SIGNAL_SetMirror(Instance* instance, void* signal);
int SIGNAL_FogNear(Instance* instance, void* signal);
int SIGNAL_FogFar(Instance* instance, void* signal);
int SIGNAL_StartVertexMorph(Instance* instance, void* signal);
int SIGNAL_StopVertexMorph(Instance* instance, void* signal);
int SIGNAL_LogicValue(Instance* instance, void* signal);
int SIGNAL_CameraShake(Instance* instance, void* signal);
int SIGNAL_LogicAnd(Instance* instance, void* signal);
int SIGNAL_LogicOr(Instance* instance, void* signal);
int SIGNAL_LogicXor(Instance* instance, void* signal);
int SIGNAL_LogicTrue(Instance* instance, void* signal);
int SIGNAL_LogicFalse(Instance* instance, void* signal);
int SIGNAL_CallSignal(Instance* instance, void* signal);
int SIGNAL_Offset(Instance* instance, void* signal);
int SIGNAL_LogicAdd(Instance* instance, void* signal);
int SIGNAL_LogicSub(Instance* instance, void* signal);
int SIGNAL_Goto(Instance* instance, void* signal);
int SIGNAL_Label(Instance* instance, void* signal);
int SIGNAL_End(Instance* instance, void* signal);
int SIGNAL_GoSub(Instance* instance, void* signal);
int SIGNAL_StopPlayerControl(Instance* instance, void* signal);
int SIGNAL_StartPlayerControl(Instance* instance, void* signal);
int SIGNAL_SetPlayerControl(Instance* instance, void* signal);
int SIGNAL_Launch(Instance* instance, void* signal);
int SIGNAL_CostumeChange(Instance* instance, void* signal);
int SIGNAL_GameValue(Instance* instance, void* signal);
int SIGNAL_SetZSignal(Instance* instance, void* signal);
int SIGNAL_ResetZSignal(Instance* instance, void* signal);
int SIGNAL_SoundEffect(Instance* instance, void* signal);
int SIGNAL_MusicControl(Instance* instance, void* signal);
int SIGNAL_LevelChange(Instance* instance, void* signal);
int SIGNAL_VoiceControl(Instance* instance, void* signal);
int SIGNAL_BankChange(Instance* instance, void* signal);
int SIGNAL_GameLoadSave(Instance* instance, void* signal);
int SIGNAL_HideObjectGroup(Instance* instance, void* signal);
int SIGNAL_UnhideObjectGroup(Instance* instance, void* signal);
int SIGNAL_Shards(Instance* instance, void* signal);
int SIGNAL_CameraSpline(Instance* instance, void* signal);
int SIGNAL_ScreenWipe(Instance* instance, void* signal);
int SIGNAL_VoiceQueue(Instance* instance, void* signal);
int SIGNAL_VoiceUnQueue(Instance* instance, void* signal);
int SIGNAL_VoiceRequest(Instance* instance, void* signal);
int SIGNAL_VoiceClearQueue(Instance* instance, void* signal);
int SIGNAL_VoiceForce(Instance* instance, void* signal);
int SIGNAL_SetMusicVariable(Instance* instance, void* signal);
int SIGNAL_IntroActive(Instance* instance, void* signal);
int SIGNAL_IntroFX(Instance* instance, void* signal);
int SIGNAL_GotoPos(Instance* instance, void* signal);
int SIGNAL_Frame(Instance* instance, void* signal);
int SIGNAL_BirthObject(Instance* instance, void* signal);
int SIGNAL_BlendStart(Instance* instance, void* signal);
int SIGNAL_MiscValue(Instance* instance, void* signal);
int SIGNAL_VoiceDisable(Instance* instance, void* signal);
int SIGNAL_VoiceReEnable(Instance* instance, void* signal);
int SIGNAL_SetTimes(Instance* instance, void* signal);
int SIGNAL_ScreenWipeColor(Instance* instance, void* signal);
int SIGNAL_Relocate(Instance* instance, void* signal);
int SIGNAL_LogicTrueElse(Instance* instance, void* signal);
int SIGNAL_LogicFalseElse(Instance* instance, void* signal);
int SIGNAL_Print(Instance* instance, void* signal);
int SIGNAL_TagTimer(Instance* instance, void* signal);
int SIGNAL_SetNoRemove(Instance* instance, void* signal);
int SIGNAL_ResetNoRemove(Instance* instance, void* signal);
int SIGNAL_8004E95C(Instance* instance, void* signal);
int SIGNAL_8004C844(Instance* instance, void* signal);
int SIGNAL_8004CFC8(Instance* instance, void* signal);
int SIGNAL_8004E9A8(Instance* instance, void* signal);
int SIGNAL_8004E9BC(Instance* instance, void* signal);
int SIGNAL_8004E9D0(Instance* instance, void* signal);
int SIGNAL_8004E9E4(Instance* instance, void* signal);
int SIGNAL_8004E9F8(Instance* instance, void* signal);
int SIGNAL_8004EA2C(Instance* instance, void* signal);

#endif
