name: ReportCI

on:
  push:
    branches: [ "objdiff" ]
  pull_request:
    branches: [ "objdiff" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch secrets
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.TOKEN }}
          path: secret

      - name: Intall packages
        run: sudo apt-get install -y git make git build-essential binutils-mips-linux-gnu python3 python3-pip

      - name: Install Python modules
        run: pip install -r requirements.txt

      - name: Setup project
        run: |
          make clean
          make splitobjdiff
          make buildobjdiff
          make generatediffjson

      - name: Generate report
        run: make report

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: US_report
          path: build/report.json
        
